
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.pondersroleplaymod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.pondersroleplaymod.block.WrenchBlockBlock;
import net.mcreator.pondersroleplaymod.block.WoodenBoards3Block;
import net.mcreator.pondersroleplaymod.block.WoodenBoards2Block;
import net.mcreator.pondersroleplaymod.block.WoodenBoards1Block;
import net.mcreator.pondersroleplaymod.block.WaterPuddleBlock;
import net.mcreator.pondersroleplaymod.block.WallBroomDustpanBlock;
import net.mcreator.pondersroleplaymod.block.WallBroomBlock;
import net.mcreator.pondersroleplaymod.block.TrashbinStage2Block;
import net.mcreator.pondersroleplaymod.block.TrashbinStage1Block;
import net.mcreator.pondersroleplaymod.block.TrashBinStage3Block;
import net.mcreator.pondersroleplaymod.block.TrashBinEmptyBlock;
import net.mcreator.pondersroleplaymod.block.TrashBagBoxOpenBlock;
import net.mcreator.pondersroleplaymod.block.TrashBagBoxClosedBlock;
import net.mcreator.pondersroleplaymod.block.Trash5Block;
import net.mcreator.pondersroleplaymod.block.Trash4Block;
import net.mcreator.pondersroleplaymod.block.Trash3Block;
import net.mcreator.pondersroleplaymod.block.Trash2Block;
import net.mcreator.pondersroleplaymod.block.Trash1Block;
import net.mcreator.pondersroleplaymod.block.ToolWallWrenchBlock;
import net.mcreator.pondersroleplaymod.block.ToolWallTapeBlock;
import net.mcreator.pondersroleplaymod.block.ToolWallPowerDrillBlock;
import net.mcreator.pondersroleplaymod.block.ToolWallPScrewdriverBlock;
import net.mcreator.pondersroleplaymod.block.ToolWallMonkeyWrenchBlock;
import net.mcreator.pondersroleplaymod.block.ToolWallHandSawBlock;
import net.mcreator.pondersroleplaymod.block.ToolWallHammerBlock;
import net.mcreator.pondersroleplaymod.block.ToolWallFScrewdriverBlock;
import net.mcreator.pondersroleplaymod.block.ToolWallEmptyBlock;
import net.mcreator.pondersroleplaymod.block.ToolWallCrowbarBlock;
import net.mcreator.pondersroleplaymod.block.ToolWallBoxCutterBlock;
import net.mcreator.pondersroleplaymod.block.ToolDrawerBlock;
import net.mcreator.pondersroleplaymod.block.TapeBlockBlock;
import net.mcreator.pondersroleplaymod.block.TableLongMiddleBlock;
import net.mcreator.pondersroleplaymod.block.TableLongBlock;
import net.mcreator.pondersroleplaymod.block.TableBlock;
import net.mcreator.pondersroleplaymod.block.TableAnd4ChairsBlock;
import net.mcreator.pondersroleplaymod.block.TableAnd2ChairsBlock;
import net.mcreator.pondersroleplaymod.block.SodaFillYellowBlock;
import net.mcreator.pondersroleplaymod.block.SodaFillRedBlock;
import net.mcreator.pondersroleplaymod.block.SodaFillGreenBlock;
import net.mcreator.pondersroleplaymod.block.SodaFillBlueBlock;
import net.mcreator.pondersroleplaymod.block.SodaDispensorBlock;
import net.mcreator.pondersroleplaymod.block.SkeeBallRampBlock;
import net.mcreator.pondersroleplaymod.block.SkeeBallGoalBlock;
import net.mcreator.pondersroleplaymod.block.SkeeBallBaseBlock;
import net.mcreator.pondersroleplaymod.block.SinkBlock;
import net.mcreator.pondersroleplaymod.block.ShadowBlock;
import net.mcreator.pondersroleplaymod.block.PowerDrillBlockStandingBlock;
import net.mcreator.pondersroleplaymod.block.PowerDrillBlockBlock;
import net.mcreator.pondersroleplaymod.block.Popcornmakertop1Block;
import net.mcreator.pondersroleplaymod.block.PopcornmakerdrawerBlock;
import net.mcreator.pondersroleplaymod.block.PopcornmachineDrawerBlock;
import net.mcreator.pondersroleplaymod.block.PopcornMakerTop4Block;
import net.mcreator.pondersroleplaymod.block.PopcornMakerTop3Block;
import net.mcreator.pondersroleplaymod.block.PopcornMakerTop2Block;
import net.mcreator.pondersroleplaymod.block.PopcornMachineOilBlock;
import net.mcreator.pondersroleplaymod.block.PopcornButterMachineBlock;
import net.mcreator.pondersroleplaymod.block.PoopPuddleBlock;
import net.mcreator.pondersroleplaymod.block.PlatesBlock;
import net.mcreator.pondersroleplaymod.block.Plates9Block;
import net.mcreator.pondersroleplaymod.block.Plates8Block;
import net.mcreator.pondersroleplaymod.block.Plates7Block;
import net.mcreator.pondersroleplaymod.block.Plates6Block;
import net.mcreator.pondersroleplaymod.block.Plates5Block;
import net.mcreator.pondersroleplaymod.block.Plates4Block;
import net.mcreator.pondersroleplaymod.block.Plates3Block;
import net.mcreator.pondersroleplaymod.block.Plates2Block;
import net.mcreator.pondersroleplaymod.block.Plates11Block;
import net.mcreator.pondersroleplaymod.block.Plates10Block;
import net.mcreator.pondersroleplaymod.block.PickleJarOpenBlock;
import net.mcreator.pondersroleplaymod.block.PickleJarClosedBlock;
import net.mcreator.pondersroleplaymod.block.PhoneRestingBlock;
import net.mcreator.pondersroleplaymod.block.PhoneAnsweredBlock;
import net.mcreator.pondersroleplaymod.block.PhillipsHeadBlockBlock;
import net.mcreator.pondersroleplaymod.block.PepsiMachineBlock;
import net.mcreator.pondersroleplaymod.block.PeePuddleBlock;
import net.mcreator.pondersroleplaymod.block.PaperOpenSignBlock;
import net.mcreator.pondersroleplaymod.block.PaperClosedSignBlock;
import net.mcreator.pondersroleplaymod.block.OpenSignOnsetBlock;
import net.mcreator.pondersroleplaymod.block.OpenSignOnBlock;
import net.mcreator.pondersroleplaymod.block.OpenSignOffsetBlock;
import net.mcreator.pondersroleplaymod.block.OpenSignOffBlock;
import net.mcreator.pondersroleplaymod.block.MopandBucketBlock;
import net.mcreator.pondersroleplaymod.block.MopBucketBlock;
import net.mcreator.pondersroleplaymod.block.MonkeyWrenchBlockBlock;
import net.mcreator.pondersroleplaymod.block.MetalFoldedUpChairStackBlock;
import net.mcreator.pondersroleplaymod.block.MetalFoldedUpChairBlock;
import net.mcreator.pondersroleplaymod.block.MetalFoldUpChairBlock;
import net.mcreator.pondersroleplaymod.block.IceCreamMachineTopBlock;
import net.mcreator.pondersroleplaymod.block.IceCreamMachineBottomBlock;
import net.mcreator.pondersroleplaymod.block.HomeDepotBoxOpenBlock;
import net.mcreator.pondersroleplaymod.block.HomeDepotBoxClosedBlock;
import net.mcreator.pondersroleplaymod.block.HandSawBlockBlock;
import net.mcreator.pondersroleplaymod.block.HammerBlockBlock;
import net.mcreator.pondersroleplaymod.block.GumballmachineRedBlock;
import net.mcreator.pondersroleplaymod.block.GumballTowerRedBlock;
import net.mcreator.pondersroleplaymod.block.GumballTowerPinkBlock;
import net.mcreator.pondersroleplaymod.block.GumballTowerGreenBlock;
import net.mcreator.pondersroleplaymod.block.GumballTowerBlueBlock;
import net.mcreator.pondersroleplaymod.block.GumballMachinePinkBlock;
import net.mcreator.pondersroleplaymod.block.GumballMachineGreenBlock;
import net.mcreator.pondersroleplaymod.block.GumballMachineBlueBlock;
import net.mcreator.pondersroleplaymod.block.FullTrashBinBlock;
import net.mcreator.pondersroleplaymod.block.FrenchPress4Block;
import net.mcreator.pondersroleplaymod.block.FrenchPress3Block;
import net.mcreator.pondersroleplaymod.block.FrenchPress2Block;
import net.mcreator.pondersroleplaymod.block.FrenchPress1Block;
import net.mcreator.pondersroleplaymod.block.Folgers2Block;
import net.mcreator.pondersroleplaymod.block.Folgers1Block;
import net.mcreator.pondersroleplaymod.block.FoldedUpTableBlock;
import net.mcreator.pondersroleplaymod.block.FoldUpTableCenteredBlock;
import net.mcreator.pondersroleplaymod.block.FoldUpTableBlock;
import net.mcreator.pondersroleplaymod.block.FloorScrewsBlock;
import net.mcreator.pondersroleplaymod.block.FlatHeadBlockBlock;
import net.mcreator.pondersroleplaymod.block.FlashlightBlockOnBlock;
import net.mcreator.pondersroleplaymod.block.FlashlightBlockOffBlock;
import net.mcreator.pondersroleplaymod.block.EnclosedTrashBinOpenBlock;
import net.mcreator.pondersroleplaymod.block.EnclosedTrashBinBlock;
import net.mcreator.pondersroleplaymod.block.EnclosedTrashBinBaglessBlock;
import net.mcreator.pondersroleplaymod.block.EnclosedTrashBinBaggedBlock;
import net.mcreator.pondersroleplaymod.block.EmptyCupBlock;
import net.mcreator.pondersroleplaymod.block.DrainWaterBlock;
import net.mcreator.pondersroleplaymod.block.DrainPoopBlock;
import net.mcreator.pondersroleplaymod.block.DrainPeeBlock;
import net.mcreator.pondersroleplaymod.block.DrainBloodBlock;
import net.mcreator.pondersroleplaymod.block.DrainBlock;
import net.mcreator.pondersroleplaymod.block.DeadKidBlockBlock;
import net.mcreator.pondersroleplaymod.block.CrowbarBlockBlock;
import net.mcreator.pondersroleplaymod.block.CoffeePotMachineBlock;
import net.mcreator.pondersroleplaymod.block.CoffeePotMachine4Block;
import net.mcreator.pondersroleplaymod.block.CoffeePotMachine3Block;
import net.mcreator.pondersroleplaymod.block.CoffeePotMachine2Block;
import net.mcreator.pondersroleplaymod.block.CoffeeMakerBlock;
import net.mcreator.pondersroleplaymod.block.CoffeeMaker4Block;
import net.mcreator.pondersroleplaymod.block.CoffeeMaker3Block;
import net.mcreator.pondersroleplaymod.block.CoffeeMaker2Block;
import net.mcreator.pondersroleplaymod.block.CoffeeGrinder4Block;
import net.mcreator.pondersroleplaymod.block.CoffeeGrinder3Block;
import net.mcreator.pondersroleplaymod.block.CoffeeGrinder2Block;
import net.mcreator.pondersroleplaymod.block.CoffeeGrinder1Block;
import net.mcreator.pondersroleplaymod.block.CoffeeCupBlock;
import net.mcreator.pondersroleplaymod.block.CoffeeBeanBagOpenBlock;
import net.mcreator.pondersroleplaymod.block.CoffeeBeanBagClosedBlock;
import net.mcreator.pondersroleplaymod.block.CocacolaMachineBlock;
import net.mcreator.pondersroleplaymod.block.ClosedNoteBlock;
import net.mcreator.pondersroleplaymod.block.ClawMachineSuccessBlock;
import net.mcreator.pondersroleplaymod.block.ClawMachineFailBlock;
import net.mcreator.pondersroleplaymod.block.ClawMachineBlock;
import net.mcreator.pondersroleplaymod.block.ChangeMachineBottomBlock;
import net.mcreator.pondersroleplaymod.block.ChangeMachineBlock;
import net.mcreator.pondersroleplaymod.block.ChairTuckedBlock;
import net.mcreator.pondersroleplaymod.block.ChairBlock;
import net.mcreator.pondersroleplaymod.block.CashRegisterOpenBlock;
import net.mcreator.pondersroleplaymod.block.CashRegisterClosedBlock;
import net.mcreator.pondersroleplaymod.block.CashRegisterCardBlock;
import net.mcreator.pondersroleplaymod.block.BoxCutterBlockBlock;
import net.mcreator.pondersroleplaymod.block.BloodPuddleBlock;
import net.mcreator.pondersroleplaymod.block.BaggedTrashBinBlock;
import net.mcreator.pondersroleplaymod.block.ATMBlock;
import net.mcreator.pondersroleplaymod.PondersRoleplayModMod;

public class PondersRoleplayModModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, PondersRoleplayModMod.MODID);
	public static final RegistryObject<Block> TRASHBIN_STAGE_1 = REGISTRY.register("trashbin_stage_1", () -> new TrashbinStage1Block());
	public static final RegistryObject<Block> TRASH_BIN_EMPTY = REGISTRY.register("trash_bin_empty", () -> new TrashBinEmptyBlock());
	public static final RegistryObject<Block> TRASHBIN_STAGE_2 = REGISTRY.register("trashbin_stage_2", () -> new TrashbinStage2Block());
	public static final RegistryObject<Block> TRASH_BIN_STAGE_3 = REGISTRY.register("trash_bin_stage_3", () -> new TrashBinStage3Block());
	public static final RegistryObject<Block> FULL_TRASH_BIN = REGISTRY.register("full_trash_bin", () -> new FullTrashBinBlock());
	public static final RegistryObject<Block> BAGGED_TRASH_BIN = REGISTRY.register("bagged_trash_bin", () -> new BaggedTrashBinBlock());
	public static final RegistryObject<Block> SODA_DISPENSOR = REGISTRY.register("soda_dispensor", () -> new SodaDispensorBlock());
	public static final RegistryObject<Block> SODA_FILL_RED = REGISTRY.register("soda_fill_red", () -> new SodaFillRedBlock());
	public static final RegistryObject<Block> SODA_FILL_GREEN = REGISTRY.register("soda_fill_green", () -> new SodaFillGreenBlock());
	public static final RegistryObject<Block> SODA_FILL_BLUE = REGISTRY.register("soda_fill_blue", () -> new SodaFillBlueBlock());
	public static final RegistryObject<Block> SODA_FILL_YELLOW = REGISTRY.register("soda_fill_yellow", () -> new SodaFillYellowBlock());
	public static final RegistryObject<Block> MOPAND_BUCKET = REGISTRY.register("mopand_bucket", () -> new MopandBucketBlock());
	public static final RegistryObject<Block> MOP_BUCKET = REGISTRY.register("mop_bucket", () -> new MopBucketBlock());
	public static final RegistryObject<Block> WATER_PUDDLE = REGISTRY.register("water_puddle", () -> new WaterPuddleBlock());
	public static final RegistryObject<Block> PEE_PUDDLE = REGISTRY.register("pee_puddle", () -> new PeePuddleBlock());
	public static final RegistryObject<Block> BLOOD_PUDDLE = REGISTRY.register("blood_puddle", () -> new BloodPuddleBlock());
	public static final RegistryObject<Block> POOP_PUDDLE = REGISTRY.register("poop_puddle", () -> new PoopPuddleBlock());
	public static final RegistryObject<Block> SINK = REGISTRY.register("sink", () -> new SinkBlock());
	public static final RegistryObject<Block> DRAIN = REGISTRY.register("drain", () -> new DrainBlock());
	public static final RegistryObject<Block> DRAIN_WATER = REGISTRY.register("drain_water", () -> new DrainWaterBlock());
	public static final RegistryObject<Block> DRAIN_PEE = REGISTRY.register("drain_pee", () -> new DrainPeeBlock());
	public static final RegistryObject<Block> DRAIN_BLOOD = REGISTRY.register("drain_blood", () -> new DrainBloodBlock());
	public static final RegistryObject<Block> DRAIN_POOP = REGISTRY.register("drain_poop", () -> new DrainPoopBlock());
	public static final RegistryObject<Block> SHADOW = REGISTRY.register("shadow", () -> new ShadowBlock());
	public static final RegistryObject<Block> TRASH_BAG_BOX_CLOSED = REGISTRY.register("trash_bag_box_closed", () -> new TrashBagBoxClosedBlock());
	public static final RegistryObject<Block> TRASH_BAG_BOX_OPEN = REGISTRY.register("trash_bag_box_open", () -> new TrashBagBoxOpenBlock());
	public static final RegistryObject<Block> CASH_REGISTER_CLOSED = REGISTRY.register("cash_register_closed", () -> new CashRegisterClosedBlock());
	public static final RegistryObject<Block> CASH_REGISTER_OPEN = REGISTRY.register("cash_register_open", () -> new CashRegisterOpenBlock());
	public static final RegistryObject<Block> WALL_BROOM = REGISTRY.register("wall_broom", () -> new WallBroomBlock());
	public static final RegistryObject<Block> WALL_BROOM_DUSTPAN = REGISTRY.register("wall_broom_dustpan", () -> new WallBroomDustpanBlock());
	public static final RegistryObject<Block> TRASH_1 = REGISTRY.register("trash_1", () -> new Trash1Block());
	public static final RegistryObject<Block> TRASH_2 = REGISTRY.register("trash_2", () -> new Trash2Block());
	public static final RegistryObject<Block> TRASH_3 = REGISTRY.register("trash_3", () -> new Trash3Block());
	public static final RegistryObject<Block> TRASH_4 = REGISTRY.register("trash_4", () -> new Trash4Block());
	public static final RegistryObject<Block> TRASH_5 = REGISTRY.register("trash_5", () -> new Trash5Block());
	public static final RegistryObject<Block> WOODEN_BOARDS_3 = REGISTRY.register("wooden_boards_3", () -> new WoodenBoards3Block());
	public static final RegistryObject<Block> WOODEN_BOARDS_2 = REGISTRY.register("wooden_boards_2", () -> new WoodenBoards2Block());
	public static final RegistryObject<Block> WOODEN_BOARDS_1 = REGISTRY.register("wooden_boards_1", () -> new WoodenBoards1Block());
	public static final RegistryObject<Block> CLOSED_NOTE = REGISTRY.register("closed_note", () -> new ClosedNoteBlock());
	public static final RegistryObject<Block> PAPER_OPEN_SIGN = REGISTRY.register("paper_open_sign", () -> new PaperOpenSignBlock());
	public static final RegistryObject<Block> PAPER_CLOSED_SIGN = REGISTRY.register("paper_closed_sign", () -> new PaperClosedSignBlock());
	public static final RegistryObject<Block> PLATES = REGISTRY.register("plates", () -> new PlatesBlock());
	public static final RegistryObject<Block> PLATES_2 = REGISTRY.register("plates_2", () -> new Plates2Block());
	public static final RegistryObject<Block> PLATES_3 = REGISTRY.register("plates_3", () -> new Plates3Block());
	public static final RegistryObject<Block> PLATES_4 = REGISTRY.register("plates_4", () -> new Plates4Block());
	public static final RegistryObject<Block> PLATES_5 = REGISTRY.register("plates_5", () -> new Plates5Block());
	public static final RegistryObject<Block> PLATES_6 = REGISTRY.register("plates_6", () -> new Plates6Block());
	public static final RegistryObject<Block> PLATES_7 = REGISTRY.register("plates_7", () -> new Plates7Block());
	public static final RegistryObject<Block> PLATES_8 = REGISTRY.register("plates_8", () -> new Plates8Block());
	public static final RegistryObject<Block> PLATES_9 = REGISTRY.register("plates_9", () -> new Plates9Block());
	public static final RegistryObject<Block> PLATES_10 = REGISTRY.register("plates_10", () -> new Plates10Block());
	public static final RegistryObject<Block> PLATES_11 = REGISTRY.register("plates_11", () -> new Plates11Block());
	public static final RegistryObject<Block> HOME_DEPOT_BOX_OPEN = REGISTRY.register("home_depot_box_open", () -> new HomeDepotBoxOpenBlock());
	public static final RegistryObject<Block> HOME_DEPOT_BOX_CLOSED = REGISTRY.register("home_depot_box_closed", () -> new HomeDepotBoxClosedBlock());
	public static final RegistryObject<Block> PICKLE_JAR_CLOSED = REGISTRY.register("pickle_jar_closed", () -> new PickleJarClosedBlock());
	public static final RegistryObject<Block> PICKLE_JAR_OPEN = REGISTRY.register("pickle_jar_open", () -> new PickleJarOpenBlock());
	public static final RegistryObject<Block> TABLE_AND_2_CHAIRS = REGISTRY.register("table_and_2_chairs", () -> new TableAnd2ChairsBlock());
	public static final RegistryObject<Block> ENCLOSED_TRASH_BIN = REGISTRY.register("enclosed_trash_bin", () -> new EnclosedTrashBinBlock());
	public static final RegistryObject<Block> ENCLOSED_TRASH_BIN_OPEN = REGISTRY.register("enclosed_trash_bin_open", () -> new EnclosedTrashBinOpenBlock());
	public static final RegistryObject<Block> ENCLOSED_TRASH_BIN_BAGLESS = REGISTRY.register("enclosed_trash_bin_bagless", () -> new EnclosedTrashBinBaglessBlock());
	public static final RegistryObject<Block> ENCLOSED_TRASH_BIN_BAGGED = REGISTRY.register("enclosed_trash_bin_bagged", () -> new EnclosedTrashBinBaggedBlock());
	public static final RegistryObject<Block> TABLE_AND_4_CHAIRS = REGISTRY.register("table_and_4_chairs", () -> new TableAnd4ChairsBlock());
	public static final RegistryObject<Block> CHAIR = REGISTRY.register("chair", () -> new ChairBlock());
	public static final RegistryObject<Block> CHAIR_TUCKED = REGISTRY.register("chair_tucked", () -> new ChairTuckedBlock());
	public static final RegistryObject<Block> TABLE = REGISTRY.register("table", () -> new TableBlock());
	public static final RegistryObject<Block> TABLE_LONG = REGISTRY.register("table_long", () -> new TableLongBlock());
	public static final RegistryObject<Block> TABLE_LONG_MIDDLE = REGISTRY.register("table_long_middle", () -> new TableLongMiddleBlock());
	public static final RegistryObject<Block> METAL_FOLD_UP_CHAIR = REGISTRY.register("metal_fold_up_chair", () -> new MetalFoldUpChairBlock());
	public static final RegistryObject<Block> METAL_FOLDED_UP_CHAIR = REGISTRY.register("metal_folded_up_chair", () -> new MetalFoldedUpChairBlock());
	public static final RegistryObject<Block> FOLD_UP_TABLE = REGISTRY.register("fold_up_table", () -> new FoldUpTableBlock());
	public static final RegistryObject<Block> FOLD_UP_TABLE_CENTERED = REGISTRY.register("fold_up_table_centered", () -> new FoldUpTableCenteredBlock());
	public static final RegistryObject<Block> FOLDED_UP_TABLE = REGISTRY.register("folded_up_table", () -> new FoldedUpTableBlock());
	public static final RegistryObject<Block> CASH_REGISTER_CARD = REGISTRY.register("cash_register_card", () -> new CashRegisterCardBlock());
	public static final RegistryObject<Block> METAL_FOLDED_UP_CHAIR_STACK = REGISTRY.register("metal_folded_up_chair_stack", () -> new MetalFoldedUpChairStackBlock());
	public static final RegistryObject<Block> OPEN_SIGN_ON = REGISTRY.register("open_sign_on", () -> new OpenSignOnBlock());
	public static final RegistryObject<Block> OPEN_SIGN_OFF = REGISTRY.register("open_sign_off", () -> new OpenSignOffBlock());
	public static final RegistryObject<Block> PHONE_RESTING = REGISTRY.register("phone_resting", () -> new PhoneRestingBlock());
	public static final RegistryObject<Block> PHONE_ANSWERED = REGISTRY.register("phone_answered", () -> new PhoneAnsweredBlock());
	public static final RegistryObject<Block> COFFEE_MAKER = REGISTRY.register("coffee_maker", () -> new CoffeeMakerBlock());
	public static final RegistryObject<Block> COFFEE_MAKER_2 = REGISTRY.register("coffee_maker_2", () -> new CoffeeMaker2Block());
	public static final RegistryObject<Block> COFFEE_MAKER_3 = REGISTRY.register("coffee_maker_3", () -> new CoffeeMaker3Block());
	public static final RegistryObject<Block> COFFEE_MAKER_4 = REGISTRY.register("coffee_maker_4", () -> new CoffeeMaker4Block());
	public static final RegistryObject<Block> COFFEE_CUP = REGISTRY.register("coffee_cup", () -> new CoffeeCupBlock());
	public static final RegistryObject<Block> EMPTY_CUP = REGISTRY.register("empty_cup", () -> new EmptyCupBlock());
	public static final RegistryObject<Block> COFFEE_POT_MACHINE = REGISTRY.register("coffee_pot_machine", () -> new CoffeePotMachineBlock());
	public static final RegistryObject<Block> COFFEE_POT_MACHINE_2 = REGISTRY.register("coffee_pot_machine_2", () -> new CoffeePotMachine2Block());
	public static final RegistryObject<Block> COFFEE_POT_MACHINE_3 = REGISTRY.register("coffee_pot_machine_3", () -> new CoffeePotMachine3Block());
	public static final RegistryObject<Block> COFFEE_POT_MACHINE_4 = REGISTRY.register("coffee_pot_machine_4", () -> new CoffeePotMachine4Block());
	public static final RegistryObject<Block> COFFEE_BEAN_BAG_CLOSED = REGISTRY.register("coffee_bean_bag_closed", () -> new CoffeeBeanBagClosedBlock());
	public static final RegistryObject<Block> COFFEE_BEAN_BAG_OPEN = REGISTRY.register("coffee_bean_bag_open", () -> new CoffeeBeanBagOpenBlock());
	public static final RegistryObject<Block> COFFEE_GRINDER_1 = REGISTRY.register("coffee_grinder_1", () -> new CoffeeGrinder1Block());
	public static final RegistryObject<Block> COFFEE_GRINDER_2 = REGISTRY.register("coffee_grinder_2", () -> new CoffeeGrinder2Block());
	public static final RegistryObject<Block> COFFEE_GRINDER_3 = REGISTRY.register("coffee_grinder_3", () -> new CoffeeGrinder3Block());
	public static final RegistryObject<Block> COFFEE_GRINDER_4 = REGISTRY.register("coffee_grinder_4", () -> new CoffeeGrinder4Block());
	public static final RegistryObject<Block> FOLGERS_1 = REGISTRY.register("folgers_1", () -> new Folgers1Block());
	public static final RegistryObject<Block> FOLGERS_2 = REGISTRY.register("folgers_2", () -> new Folgers2Block());
	public static final RegistryObject<Block> FRENCH_PRESS_1 = REGISTRY.register("french_press_1", () -> new FrenchPress1Block());
	public static final RegistryObject<Block> FRENCH_PRESS_2 = REGISTRY.register("french_press_2", () -> new FrenchPress2Block());
	public static final RegistryObject<Block> FRENCH_PRESS_3 = REGISTRY.register("french_press_3", () -> new FrenchPress3Block());
	public static final RegistryObject<Block> FRENCH_PRESS_4 = REGISTRY.register("french_press_4", () -> new FrenchPress4Block());
	public static final RegistryObject<Block> POPCORNMAKERTOP_1 = REGISTRY.register("popcornmakertop_1", () -> new Popcornmakertop1Block());
	public static final RegistryObject<Block> POPCORN_MAKER_TOP_2 = REGISTRY.register("popcorn_maker_top_2", () -> new PopcornMakerTop2Block());
	public static final RegistryObject<Block> POPCORN_MAKER_TOP_3 = REGISTRY.register("popcorn_maker_top_3", () -> new PopcornMakerTop3Block());
	public static final RegistryObject<Block> POPCORN_MAKER_TOP_4 = REGISTRY.register("popcorn_maker_top_4", () -> new PopcornMakerTop4Block());
	public static final RegistryObject<Block> POPCORNMAKERDRAWER = REGISTRY.register("popcornmakerdrawer", () -> new PopcornmakerdrawerBlock());
	public static final RegistryObject<Block> POPCORNMACHINE_DRAWER = REGISTRY.register("popcornmachine_drawer", () -> new PopcornmachineDrawerBlock());
	public static final RegistryObject<Block> POPCORN_MACHINE_OIL = REGISTRY.register("popcorn_machine_oil", () -> new PopcornMachineOilBlock());
	public static final RegistryObject<Block> POPCORN_BUTTER_MACHINE = REGISTRY.register("popcorn_butter_machine", () -> new PopcornButterMachineBlock());
	public static final RegistryObject<Block> ATM = REGISTRY.register("atm", () -> new ATMBlock());
	public static final RegistryObject<Block> CHANGE_MACHINE = REGISTRY.register("change_machine", () -> new ChangeMachineBlock());
	public static final RegistryObject<Block> CHANGE_MACHINE_BOTTOM = REGISTRY.register("change_machine_bottom", () -> new ChangeMachineBottomBlock());
	public static final RegistryObject<Block> OPEN_SIGN_ONSET = REGISTRY.register("open_sign_onset", () -> new OpenSignOnsetBlock());
	public static final RegistryObject<Block> OPEN_SIGN_OFFSET = REGISTRY.register("open_sign_offset", () -> new OpenSignOffsetBlock());
	public static final RegistryObject<Block> CLAW_MACHINE = REGISTRY.register("claw_machine", () -> new ClawMachineBlock());
	public static final RegistryObject<Block> CLAW_MACHINE_SUCCESS = REGISTRY.register("claw_machine_success", () -> new ClawMachineSuccessBlock());
	public static final RegistryObject<Block> CLAW_MACHINE_FAIL = REGISTRY.register("claw_machine_fail", () -> new ClawMachineFailBlock());
	public static final RegistryObject<Block> SKEE_BALL_BASE = REGISTRY.register("skee_ball_base", () -> new SkeeBallBaseBlock());
	public static final RegistryObject<Block> SKEE_BALL_RAMP = REGISTRY.register("skee_ball_ramp", () -> new SkeeBallRampBlock());
	public static final RegistryObject<Block> SKEE_BALL_GOAL = REGISTRY.register("skee_ball_goal", () -> new SkeeBallGoalBlock());
	public static final RegistryObject<Block> GUMBALLMACHINE_RED = REGISTRY.register("gumballmachine_red", () -> new GumballmachineRedBlock());
	public static final RegistryObject<Block> GUMBALL_MACHINE_BLUE = REGISTRY.register("gumball_machine_blue", () -> new GumballMachineBlueBlock());
	public static final RegistryObject<Block> GUMBALL_MACHINE_GREEN = REGISTRY.register("gumball_machine_green", () -> new GumballMachineGreenBlock());
	public static final RegistryObject<Block> GUMBALL_MACHINE_PINK = REGISTRY.register("gumball_machine_pink", () -> new GumballMachinePinkBlock());
	public static final RegistryObject<Block> GUMBALL_TOWER_RED = REGISTRY.register("gumball_tower_red", () -> new GumballTowerRedBlock());
	public static final RegistryObject<Block> GUMBALL_TOWER_BLUE = REGISTRY.register("gumball_tower_blue", () -> new GumballTowerBlueBlock());
	public static final RegistryObject<Block> GUMBALL_TOWER_GREEN = REGISTRY.register("gumball_tower_green", () -> new GumballTowerGreenBlock());
	public static final RegistryObject<Block> GUMBALL_TOWER_PINK = REGISTRY.register("gumball_tower_pink", () -> new GumballTowerPinkBlock());
	public static final RegistryObject<Block> PEPSI_MACHINE = REGISTRY.register("pepsi_machine", () -> new PepsiMachineBlock());
	public static final RegistryObject<Block> COCACOLA_MACHINE = REGISTRY.register("cocacola_machine", () -> new CocacolaMachineBlock());
	public static final RegistryObject<Block> ICE_CREAM_MACHINE_BOTTOM = REGISTRY.register("ice_cream_machine_bottom", () -> new IceCreamMachineBottomBlock());
	public static final RegistryObject<Block> ICE_CREAM_MACHINE_TOP = REGISTRY.register("ice_cream_machine_top", () -> new IceCreamMachineTopBlock());
	public static final RegistryObject<Block> HAMMER_BLOCK = REGISTRY.register("hammer_block", () -> new HammerBlockBlock());
	public static final RegistryObject<Block> CROWBAR_BLOCK = REGISTRY.register("crowbar_block", () -> new CrowbarBlockBlock());
	public static final RegistryObject<Block> BOX_CUTTER_BLOCK = REGISTRY.register("box_cutter_block", () -> new BoxCutterBlockBlock());
	public static final RegistryObject<Block> HAND_SAW_BLOCK = REGISTRY.register("hand_saw_block", () -> new HandSawBlockBlock());
	public static final RegistryObject<Block> MONKEY_WRENCH_BLOCK = REGISTRY.register("monkey_wrench_block", () -> new MonkeyWrenchBlockBlock());
	public static final RegistryObject<Block> POWER_DRILL_BLOCK = REGISTRY.register("power_drill_block", () -> new PowerDrillBlockBlock());
	public static final RegistryObject<Block> POWER_DRILL_BLOCK_STANDING = REGISTRY.register("power_drill_block_standing", () -> new PowerDrillBlockStandingBlock());
	public static final RegistryObject<Block> WRENCH_BLOCK = REGISTRY.register("wrench_block", () -> new WrenchBlockBlock());
	public static final RegistryObject<Block> TAPE_BLOCK = REGISTRY.register("tape_block", () -> new TapeBlockBlock());
	public static final RegistryObject<Block> FLAT_HEAD_BLOCK = REGISTRY.register("flat_head_block", () -> new FlatHeadBlockBlock());
	public static final RegistryObject<Block> PHILLIPS_HEAD_BLOCK = REGISTRY.register("phillips_head_block", () -> new PhillipsHeadBlockBlock());
	public static final RegistryObject<Block> FLASHLIGHT_BLOCK_ON = REGISTRY.register("flashlight_block_on", () -> new FlashlightBlockOnBlock());
	public static final RegistryObject<Block> FLASHLIGHT_BLOCK_OFF = REGISTRY.register("flashlight_block_off", () -> new FlashlightBlockOffBlock());
	public static final RegistryObject<Block> FLOOR_SCREWS = REGISTRY.register("floor_screws", () -> new FloorScrewsBlock());
	public static final RegistryObject<Block> TOOL_DRAWER = REGISTRY.register("tool_drawer", () -> new ToolDrawerBlock());
	public static final RegistryObject<Block> TOOL_WALL_EMPTY = REGISTRY.register("tool_wall_empty", () -> new ToolWallEmptyBlock());
	public static final RegistryObject<Block> TOOL_WALL_HAMMER = REGISTRY.register("tool_wall_hammer", () -> new ToolWallHammerBlock());
	public static final RegistryObject<Block> TOOL_WALL_TAPE = REGISTRY.register("tool_wall_tape", () -> new ToolWallTapeBlock());
	public static final RegistryObject<Block> TOOL_WALL_BOX_CUTTER = REGISTRY.register("tool_wall_box_cutter", () -> new ToolWallBoxCutterBlock());
	public static final RegistryObject<Block> TOOL_WALL_CROWBAR = REGISTRY.register("tool_wall_crowbar", () -> new ToolWallCrowbarBlock());
	public static final RegistryObject<Block> TOOL_WALL_HAND_SAW = REGISTRY.register("tool_wall_hand_saw", () -> new ToolWallHandSawBlock());
	public static final RegistryObject<Block> TOOL_WALL_MONKEY_WRENCH = REGISTRY.register("tool_wall_monkey_wrench", () -> new ToolWallMonkeyWrenchBlock());
	public static final RegistryObject<Block> TOOL_WALL_WRENCH = REGISTRY.register("tool_wall_wrench", () -> new ToolWallWrenchBlock());
	public static final RegistryObject<Block> TOOL_WALL_POWER_DRILL = REGISTRY.register("tool_wall_power_drill", () -> new ToolWallPowerDrillBlock());
	public static final RegistryObject<Block> TOOL_WALL_P_SCREWDRIVER = REGISTRY.register("tool_wall_p_screwdriver", () -> new ToolWallPScrewdriverBlock());
	public static final RegistryObject<Block> TOOL_WALL_F_SCREWDRIVER = REGISTRY.register("tool_wall_f_screwdriver", () -> new ToolWallFScrewdriverBlock());
	public static final RegistryObject<Block> DEAD_KID_BLOCK = REGISTRY.register("dead_kid_block", () -> new DeadKidBlockBlock());
}
